### ISSUE TITLE
after image generation, image is still in tmp folder & tmp folder is not deleted

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk-mediagen#7]
image should be moved after completion to the file specified in the component meta file.

tmp folder should be removed after completion

**Comment by obbardc** [comment]
Also the image has not got the right owner or permissions.

**Comment by danielhjames** [comment]
Maybe we need a command something like 'make release' to perform the image move, as we might need to test that image in tmp/ before releasing it to the users. Should 'make clean' remove the tmp/ directory and previously built images? Or is that too risky if someone has not made the release yet?

**Comment by obbardc** [comment]
This is now fixed.
