### ISSUE TITLE
postinst.sh should use existing package metadata for installing

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk-mediagen#9]
Currently we duplicate the list of packages which must be installed when building an image.

**Comment by obbardc** [comment]
I have begun implementing this by implementing the `pdk dumpcomps` command

**Comment by obbardc** [comment]
Hi @danielhjames I have implemented the code so the postinst no longer has to reference packages. The system install automatically all packages referenced by components listed in the top-level project file :-)

I have also modified the pideck-distro project to match.

**Comment by danielhjames** [comment]
Great improvement, thanks @obbardc !
